name: async_parallel_queue
description: Library to enqueue async callbacks to be executed in order. You can await for they completion and/or cancel the execution by id.
version: 1.0.3
homepage: https://github.com/sthefanoss/async_parallel_queue

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  quiver: ^3.0.0

dev_dependencies:
  lints:
  test:
