name: async_parallel_queue
description: Handle async calls in order with a number of workers.
version: 1.0.1
homepage: https://github.com/sthefanoss/async_parallel_queue

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
